modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/Hanekmio/Teleport-Master-SimpCommands/issues"

[[mods]]
modId="tpmaster"
version="20.1.0-SC"
displayName="Teleport Master"
logoFile="logo.png"
credits="Liu Dongyu; Simplified commands by Hanekmio"
authors="Hexagram"

description='''
This mod adds some commands for teleporting.
'''

[[dependencies.tpmaster]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.tpmaster]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
